
---
- name: Deploy Apache Web Server on Fedora hosts
  hosts: fedora
  become: yes
  become_method: sudo
  
  tasks:
  - name: Install Apache
    dnf:
      name: httpd
      state: present

  vars_files:
  - vars/linuxsecrets.yml

  
  - name: Copy the local web content to the remote system
    copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: root
      group: root
      mode: 0644
    with_items:
      - src: index.html
        dest: /var/www/html/index.html
        
  - name: Ensure Apache is running and started at boot time
    service:
      name: httpd
      state: started
      enabled: yes
  
